language: python
cache: pip

matrix:
  include:
    - python: 3.9-dev
    - python: 3.8
    - python: 3.7
    - python: 3.6
  fast_finish: true

install:
 - pip install -U pip
 - pip install -U black coverage coveralls flake8

script:
 # Unit tests
 - coverage run --source=fino ./test_fino.py -v

 # Static analysis
 - flake8 --statistics --count
 - black --check --diff --target-version py36 .

after_success:
 - coveralls

after_script:
 - coverage report
